---
- block:
  - name: update apt cache
    apt:
      update_cache: yes

  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist

  - name: install system packages
    apt:
      name: "{{ item }}"
      state: latest
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - pip
      - software-properties-common
      - python3-pip
      - python3-setuptools
  tags: setup
