---
- name: Master and slave requirements
  hosts: masters,slave
  become: yes
  gather_facts: yes
  become_method: sudo
  vars_files:
    - group_vars/masters.yml
    - group_vars/slave.yml

  roles:
    #- { role: system-setup }
    #- { role: docker }
    #- { role: k8s-setup }
    #- { role: helm }
