---
- block:
  - include_tasks: dependencies.yml

  - name: Install Docker Engine.
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: yes

  - name: Ensure Docker is started and enabled at boot.
    service:
      name: docker
      state: "{{ docker_service_state }}"
      enabled: "{{ docker_service_enabled }}"

  - name: Ensure handlers are notified now to avoid firewall conflicts.
    meta: flush_handlers

  - include_tasks: user.yml
    when: remote_user | length > 0

  tags: docker
